In [3]:
input_seconds = int(input("Enter time in seconds:"))
def convert_seconds(seconds):
    hours = seconds // 3600
    remainder = seconds % 3600
    minutes = remainder // 60
    seconds = remainder % 60
    return hours, minutes, seconds



hours, minutes, seconds = convert_seconds(input_seconds)

print(f"{hours} Hours {minutes} Minutes {seconds} Seconds")


2 Hours 3 Minutes 4 Seconds


In [6]:
def hollow_pyramid(rows):
    for i in range(1, rows + 1):
        for j in range(1, i + 1):
            if j == 1 or j == i or i == rows:
                print(j, end=" ")
            else:
                print(" ", end=" ")
        print()


rows = int(input("Enter number of rows: "))

hollow_pyramid(rows)


1 
1 2 
1   3 
1     4 
1 2 3 4 5 


In [8]:
num = int(input("Enter a number: "))
original = num
sum = 0
while num > 0:
    digit = num % 10
    sum += digit ** 3
    num = num // 10

if sum == original:
    print(f"{original} is an Armstrong number")
else:
    print(f"{original} is not an Armstrong number")

153 is an Armstrong number


In [9]:
def input_roll_numbers(game_name):
    n = int(input(f"Enter number of {game_name} players: "))
    print(f"Enter roll numbers of {game_name} players (space-separated):")
    return set(map(int, input().split()))

def find_students(cricket_players, badminton_players):
    both_games = cricket_players.intersection(badminton_players)
    only_cricket = cricket_players - badminton_players
    at_least_one = cricket_players.union(badminton_players)
    exactly_one = cricket_players.symmetric_difference(badminton_players)

    return both_games, only_cricket, at_least_one, exactly_one

cricket_players = input_roll_numbers("cricket")
badminton_players = input_roll_numbers("badminton")

both, only_cricket, at_least_one, exactly_one = find_students(cricket_players, badminton_players)

print("Students playing both games:", sorted(both))
print("Students playing only cricket:", sorted(only_cricket))
print("Students playing at least one game:", sorted(at_least_one))
print("Students playing exactly one game:", sorted(exactly_one))


Enter roll numbers of cricket players (space-separated):
Enter roll numbers of badminton players (space-separated):
Students playing both games: [102, 103]
Students playing only cricket: [101]
Students playing at least one game: [101, 102, 103, 104, 105]
Students playing exactly one game: [101, 104, 105]


In [10]:
import numpy as np

def create_magic_square():
    magic_square = np.array([[8, 1, 6],
                              [3, 5, 7],
                              [4, 9, 2]])
    return magic_square

def verify_magic_square(square):
    row_sums = np.sum(square, axis=1)
    col_sums = np.sum(square, axis=0)
    diag_sums = [np.sum(np.diag(square)), np.sum(np.diag(np.fliplr(square)))]
    
    all_equal = (
        np.all(row_sums == row_sums[0]) and
        np.all(col_sums == col_sums[0]) and
        diag_sums[0] == diag_sums[1] == row_sums[0]
    )
    return row_sums, col_sums, diag_sums, all_equal

def rotate_square(square):
    rotated_square = np.rot90(square, k=-1)
    return rotated_square

# Main program
magic_square = create_magic_square()
print("Original Magic Square:")
print(magic_square)

row_sums, col_sums, diag_sums, is_valid = verify_magic_square(magic_square)

print(f"Sum of each row: {row_sums.tolist()}")
print(f"Sum of each column: {col_sums.tolist()}")
print(f"Diagonal sums: {diag_sums}")

if is_valid:
    print("This is a valid magic square!")
else:
    print("This is NOT a valid magic square.")

rotated_square = rotate_square(magic_square)
print("After 90 degree rotation:")
print(rotated_square)


Original Magic Square:
[[8 1 6]
 [3 5 7]
 [4 9 2]]
Sum of each row: [15, 15, 15]
Sum of each column: [15, 15, 15]
Diagonal sums: [15, 15]
This is a valid magic square!
After 90 degree rotation:
[[4 3 8]
 [9 5 1]
 [2 7 6]]


In [13]:
import pandas as pd

def main():
    data = {"Day": [], "Temperature": [], "Humidity": []}
    for i in range(1, 8):
        temp = float(input(f"Day {i} Temperature (°C): "))
        hum = int(input(f"Day {i} Humidity (%): "))
        data["Day"].append(f"Day {i}")
        data["Temperature"].append(temp)
        data["Humidity"].append(hum)
    
    df = pd.DataFrame(data)
    
    avg_temp = df["Temperature"].mean()
    avg_hum = df["Humidity"].mean()
    
    high_temp_low_hum = df[(df["Temperature"] > avg_temp) & (df["Humidity"] < avg_hum)]
    
    correlation = df["Temperature"].corr(df["Humidity"])
  
    print("\nStatistics:")
    print(f"Average Temperature: {avg_temp:.1f}°C")
    print(f"Average Humidity: {avg_hum:.0f}%")
    
    if not high_temp_low_hum.empty:
        print("Days with high temperature and low humidity:")
        for _, row in high_temp_low_hum.iterrows():
            print(f"- {row['Day']} ({row['Temperature']}°C, {row['Humidity']}%)")
    else:
        print("No days with high temperature and low humidity.")
    
    print(f"Correlation coefficient: {correlation:.2f}")

# Run the program
main()



Statistics:
Average Temperature: 33.3°C
Average Humidity: 75%
Days with high temperature and low humidity:
- Day 6 (40.0°C, 66%)
Correlation coefficient: -0.49
