In [10]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1.shape)
print(arr1)
print()

arr2 = np.array([[2],[3],[4]])
print(arr2.shape)
print(arr2)
print()

#if we perform the addition of the array, arr1=[1,2,3] and arr2 = [1,2,3,4], means having diff.dimensions, then print(arr1 + arr2) won't happen

#Rule of broadcasting is : if there are two arrays having dimensions (1,3) and (3,1) then from right side we check either there is element '1' occurs on any of the side of them, then only we can calculate the addition
#and gives the result in maximum size of elements occurs in the array i.e. (3,3)
print(arr1+arr2)


(3,)
[1 2 3]

(3, 1)
[[2]
 [3]
 [4]]

[[3 4 5]
 [4 5 6]
 [5 6 7]]


# Lets take example of (2,1) and (2,3)

In [32]:
a1 = np.array([[1],[2]])
print(a1)
print(a1.shape)
print()
a2 = np.array([[1,2,3],[2,3,4]])
print(a2)
print(a2.shape)
print()
#Now it will give the matrix in (2,3) because 2 is maximum in the dimension of a1 and 3 is max in dimension of a2
print(a1+ a2)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [2 3 4]]
(2, 3)

[[2 3 4]
 [4 5 6]]
