# Copy

In [18]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
print(a1)
print()

cp = a1.copy()
cp[1] = 20
print(cp)
print(a1)

[1 2 3 4 5 6]

[ 1 20  3  4  5  6]
[1 2 3 4 5 6]


# View

In [12]:
a2 = np.array([1,2,3,4,5,6])
print(a2)
print()
vi = a2.view()
print(vi)

[1 2 3 4 5 6]

[1 2 3 4 5 6]
