# Datatype

In [11]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)

[1 2 3]
int32


### Datatype conversion

In [16]:
arr1 = np.array([1,2,3], dtype = np.int8)
print(arr1)
print(arr1.dtype)

[1 2 3]
int8


### Shortcut datatype conversion

In [19]:
arr1 = np.array([1,2,3], dtype = "f")
print(arr1)
print(arr1.dtype)

[1. 2. 3.]
float32
