# Indexing

In [4]:
import numpy as np
arr1 = np.array([1,2,3,4])
#                0,1,2,3
#            -4,-3,-2,-1
print(arr1[2])

3


In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1,1])

5


In [10]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3[0,2,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
8


# Slicing

In [21]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
#              0,1,2,3,4,5,6,7,8
print("index 0 to 5:", a1[:6])
print("index 4 to end:", a1[4:])
print("index 1 to 6 by stepping 1:", a1[1:6:2])
print("index 0 to end by stepping 1:", a1[::2])

index 0 to 5: [1 2 3 4 5 6]
index 4 to end: [5 6 7 8 9]
index 1 to 6 by stepping 1: [2 4 6]
index 0 to end by stepping 1: [1 3 5 7 9]


#### 2D

In [28]:
a2 = np.array([[1,2,3,4,5], [3,4,8,6,9]])
print(a2[1,1:3])
print(a2[0,1::2])

[4 8]
[2 4]
