# Insert


In [17]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print()
i = np.insert(arr, 0, 10) # np.append() = it also works same as insert
print(i)
j = np.insert(arr, (1,2), 10) # if we give float value then it will not accept
print()
print(j)

[1 2 3 4 5]

[10  1  2  3  4  5]

[ 1 10  2 10  3  4  5]


#### 2D


In [25]:
arr2 = np.array([[1,2,3],[6,7,8]])
print(arr2)
i = np.insert(arr2, 2, 10, axis = 0)
j = np.insert(arr2, 2, 10, axis = 1)
print()
print(i)
print()
print(j)

[[1 2 3]
 [6 7 8]]

[[ 1  2  3]
 [ 6  7  8]
 [10 10 10]]

[[ 1  2 10  3]
 [ 6  7 10  8]]


# Delete

In [28]:
a = np.array([1,2,3,4,5])
# index       0,1,2,3,4
d = np.delete(a, 2)
print(d)

[1 2 4 5]
