# Joining

In [5]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
new = np.concatenate((a,b))
print(new)

[1 2 3 4 5 6 7 8]


In [29]:
a1 = np.array([[1,2],[5,6]])
a2 = np.array([[4,5],[9,4]])


print(a1.ndim)
print()
n= np.concatenate((a1,a2),axis = 1)
print(n)
print()
n1 = np.concatenate((a1,a2),axis = 0)
print(n1)
print()



2

[[1 2 4 5]
 [5 6 9 4]]

[[1 2]
 [5 6]
 [4 5]
 [9 4]]



In [49]:
v1 = np.array([1,2,3,4])
v2 = np.array([9,8,7,6])

new = np.stack((v1,v2),axis=0)
new1 = np.stack((v1,v2),axis = 1)
print(new)
print()
print(new1)
print()

new2 = np.hstack((v1,v2))
print(new2)
print()

new3 = np.vstack((v1,v2))
print(new3)
print(new3.ndim)
print()

new4 = np.dstack((v1,v2))
print(new4)
print(new4.ndim)

[[1 2 3 4]
 [9 8 7 6]]

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]
2

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
3


# Splitting

In [56]:
x = np.array([1,2,3,4,5,6])
print(x)
print()
r = np.array_split(x,3)
print(r)
print(type(r))
print(r[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [68]:
x2 = np.array([[1,2],[3,4],[5,6]])
j = np.array_split(x2,3)
print(j)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
