# Matrix

In [7]:
import numpy as np
m = np.matrix([[1,2],[4,3]])
n = np.matrix([[1,2],[4,5]])
print(m*n)
print()
print(m.dot(n))

[[ 9 12]
 [16 23]]

[[ 9 12]
 [16 23]]


# Array

In [10]:
a = np.array([[1,2],[4,3]])
b = np.array([[1,2],[4,5]])
print(a*b)

[[ 1  4]
 [16 15]]


# Matrix Function
#### Transpose
#### Swapaxes
#### Inverse
#### Power
#### Determinate

### Transpose

In [22]:
m1 = np.matrix([[1,2,3],[4,5,6]])
print(m1)
print()
print(np.transpose(m1))
print()
# Or we can use another function for the transpose
print(m1.T)
print()


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


# Swapaxes

In [26]:
#swapaxes() also swaps the axis
print()
print(np.swapaxes(m1,0,1)) # covert axis 0 to 1

[[1 4]
 [2 5]
 [3 6]]


# Inverse

In [31]:
z= np.matrix([[1,2],[3,4]])
print(np.linalg.inv(z))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power

In [38]:
z1 = np.matrix([[1,2],[3,5]])
print(z1)
print()

print(np.linalg.matrix_power(z1,2))

# To print indentity matrix,
print()
print(np.linalg.matrix_power(z1,0))

[[1 2]
 [3 5]]

[[ 7 12]
 [18 31]]

[[1 0]
 [0 1]]


# Determinate

In [51]:
z1 = np.matrix([[1,2],[3,5]])
print(z1)
print()
print(np.linalg.det(z1))

[[1 2]
 [3 5]]

-1.0000000000000004
