# Search

In [5]:
import numpy as np
a = np.array([1,2,3,4,4,5,6,7,8,2,3])
# index       0,1,2,3,4,5,6,7,8,9,10

print(np.where(a ==2))
print(np.where((a%2) == 0))

(array([1, 9], dtype=int64),)
(array([1, 3, 4, 6, 8, 9], dtype=int64),)


# Search Sorted Array :- position for sorting any number or no. of list 

In [22]:
a1 = np.array([1,2,3,5,6,7,8])
#index         0,1,2,3,4,5,6
x = np.searchsorted(a1,4)
print(x)
x1 = np.searchsorted(a1,4,side="left")
print(x1)
print()

x2 = np.searchsorted(a1,[4,10],side= "left")
print(x2)

3
3

[3 7]


# Sorting Array

In [31]:
arr = np.array([1,2,47,5,3,32,67,34,23])
print(np.sort(arr))
print()

#string
arr2 = np.array(["p","s","a", "d"])
print(np.sort(arr2))
print()

#2D
arr3 = np.array([[3,2,5],[4,8,5],[83,7,34]])
print(np.sort(arr3))

[ 1  2  3  5 23 32 34 47 67]

['a' 'd' 'p' 's']

[[ 2  3  5]
 [ 4  5  8]
 [ 7 34 83]]


# Filter Array

In [34]:
arr = np.array([1,2,47,5,3])
f = [True,True,False,True,True]
print(arr[f])

[1 2 5 3]
