# Shuffle

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[6 3 5 4 2 1]


# Unique

In [18]:
arr2 = np.array([1,2,2,3,4,5,1,2,5])
u = np.unique(arr2) # unique function removes all duplicates
print(u)
print()

#if we want index numbers too then
u1 = np.unique(arr2, return_index=True, return_counts=True)
print(u1)

[1 2 3 4 5]

(array([1, 2, 3, 4, 5]), array([0, 1, 3, 4, 5], dtype=int64), array([2, 3, 1, 1, 2], dtype=int64))


# Resize

In [25]:
arr3 = np.array([1,2,3,4,5,6])
print(np.resize(arr3,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


# Flatten & Ravel

In [34]:
var = np.array([[1,2,3],[5,3,4]])
print("Flatten : ", var.flatten(order="F")) #converts 2d array in single
print("Ravel: ", np.ravel(var,order="A"))

Flatten :  [1 5 2 3 3 4]
Ravel:  [1 2 3 5 3 4]
