Array

In [40]:
import numpy as np
x = [2,3,4,5]
print(x)
print(type(x))


[2, 3, 4, 5]
<class 'list'>



Convert list into array by taking input from user

In [42]:
list = []
for i in range(1,6):
    num = int(input("Enter number: "))
    list.append(num)

arr = np.array(list)
print(arr)
print(type(arr))
print(arr.ndim) #To check the dimension either 1D, or 2D, or 3D, or Multidimensional

Enter number:  1
Enter number:  2
Enter number:  3
Enter number:  4
Enter number:  5


[1 2 3 4 5]
<class 'numpy.ndarray'>
1



2D ARRAY

In [50]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(type(a))
print(a.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2



3D ARRAY

In [62]:
b = np.array([[[1,2,3], [4,5,6], [2,4,2]]])
print(b)
print(type(b))
print(b.ndim)

[[[1 2 3]
  [4 5 6]
  [2 4 2]]]
<class 'numpy.ndarray'>
3



N DIMENSION

In [66]:
n = np.array([2,2,3,4], ndmin=10) #ndmin is used for dimension declaration
print(n)
print(type(n))
print(n.ndim) #ndim is used for dimension checking

[[[[[[[[[[2 2 3 4]]]]]]]]]]
<class 'numpy.ndarray'>
10



ALL ELEMENTS OF ARRAY = 0

In [86]:
import numpy as np
arr_zero1d = np.zeros(3)
arr_zero2d = np.zeros((3,4))
arr_zero3d = np.zeros(((3,4,5)))
print(arr_zero1d)
print()
print(arr_zero2d)
print()
print(arr_zero3d)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]



ALL ELEMENTS OF ARRAY = 1

In [88]:
arr_one1d = np.ones(3)
arr_one2d = np.ones((3,4))
arr_one3d = np.ones(((3,4,5)))
print(arr_one1d)
print()
print(arr_one2d)
print()
print(arr_one3d)
print()

[1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]




EMPTY ARRAY CREATE

In [90]:
arr_empty = np.empty(4)
print(arr_empty)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.34593230e-311]




ARANGE FUNCTION- To create an array in any range

In [92]:
arr_arange = np.arange(4)
print(arr_arange)

[0 1 2 3]




DIAGONAL WITH 1 ARRAY CREATION

In [94]:
arr_diagonal = np.eye(3)
print(arr_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




LINESPACE- Creation of array with some gap

In [112]:
arr_space = np.linspace(0,20,num=5)
print(arr_space)

[ 0.  5. 10. 15. 20.]
