# Write a program to create a null vector of size 25 but the values from fifth to tenth elements are all 1.

In [6]:
import numpy as np
null_vector = np.zeros(25)
null_vector[4:10] = 1
print(null_vector)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


# Write a program to create a vector with values ranging from 5 to 20 &amp; reverse it.

In [17]:
vector = np.arange(5,21)
print(vector)
print(np.flip(vector))

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


# Write a program to create a vector with 10 random values &amp; sort first half ascending &amp; second half descending.

In [26]:
a = np.random.rand(10)
print(a)
print()
first_half = np.sort(a[:5])
second_half = np.sort(a[6:])
print(first_half)
print()
print(second_half)

[0.49079486 0.05990134 0.21547148 0.76248955 0.80222154 0.21961659
 0.88784067 0.61051815 0.99947413 0.33525616]

[0.05990134 0.21547148 0.49079486 0.76248955 0.80222154]

[0.33525616 0.61051815 0.88784067 0.99947413]
