# ARRAY WITH RANDOM NUMBERS

## rand() for 1D: generate a random value between 0 to 1

In [13]:
import numpy as np

arr_rand = np.random.rand(4)
print(arr_rand)

[0.25430901 0.94107435 0.69667717 0.66586358]


## rand() for 2D:

In [19]:
arr_rand2 = np.random.rand(2,5)
print(arr_rand2)

[[0.34714222 0.9583024  0.07167571 0.70749912 0.51717469]
 [0.66730821 0.80637026 0.72112229 0.19362277 0.7454687 ]]


## rand() for 3D:

In [25]:
arr_rand3 = np.random.rand(1,2,3)
print(arr_rand3)

[[[0.1217832  0.22734685 0.96898231]
  [0.23218537 0.40934489 0.45491408]]]


## randn(): generate a random value close to 0, either positive or negative

In [28]:
arr_randn = np.random.randn(3)
print(arr_randn)

[ 1.58701536 -0.61784526 -0.22161721]


## ranf():  the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half open interval [0.0, 1.0).= '[' it means involved i.e. 0.0 is involved BUT ')' it means less than 1.0 

In [40]:
arr_ranf = np.random.ranf(3)
print(arr_ranf)

[0.81631545 0.08966053 0.65376645]


## randint(): the function is used to generate a random number between a given range

In [45]:
arr_4 = np.random.randint(4,24,6)
print(arr_4)

[ 9 13 13  5 13 11]
